/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JABMClienteViewer.java
 *
 * Created on 02/06/2012, 11:13:24
 */
package sge.vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author Propietario
 */
public class JABMClienteViewer extends javax.swing.JInternalFrame {
    private JABMClientePresenter presenter;
    private Integer modo; 

    public  JABMClienteViewer(int modo) {
        this.modo = modo;
         initComponents();
         if (modo == 1) {
            this.setTitle("Alta Cliente");
            btnGuardar.setText("Guardar");
            fraBusqueda.setVisible(false);
            txtId.setVisible(false);
            lblId.setVisible(false);
        }else if (modo == 2) {    
            this.setTitle("Modificar Cliente");
            btnGuardar.setText("Modificar");   
            txtId.setEnabled(false);
        }else if (modo == 3) {
            this.setTitle("Baja Cliente");
            btnGuardar.setText("Borrar");
            txtId.setEnabled(false);
            txtDir.setEditable(false);
            txtCuit.setEditable(false);
            txtRazonSocial.setEditable(false);
            cboLocalidad.setEnabled(false);
            cboProvincia.setEnabled(false);
            txtTel.setEditable(false);
            txtTel2.setEditable(false);
            txtMail.setEditable(false);
        }
        //Redimensiona la ventana
        pack();
        
        
        presenter = new JABMClientePresenter(this);  
        presenter.getProvinciaHandler().stateChanged(new ChangeEvent(this));
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();  
        //obtenemos el tamaño de la ventana  
        Dimension ventana = this.getSize();  
        //para cntrar la ventana lo hacemos con el siguiente calculo  
        this.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 2);  

    }

    public JComboBox getCboLocalidad() {
        return cboLocalidad;
    }

    public void setCboLocalidad(JComboBox cboLocalidad) {
        this.cboLocalidad = cboLocalidad;
    }

    public JComboBox getCboProvincia() {
        return cboProvincia;
    }

    public void setCboProvincia(JComboBox cboProvincia) {
        this.cboProvincia = cboProvincia;
    }

    public Integer getModo() {
        return modo;
    }

    public void setModo(Integer modo) {
        this.modo = modo;
    }

    public JTextField getTxtClienteBusq() {
        return txtClienteBusq;
    }

    public void setTxtClienteBusq(JTextField txtClienteBusq) {
        this.txtClienteBusq = txtClienteBusq;
    }

    public JTextField getTxtCuit() {
        return txtCuit;
    }

    public void setTxtCuit(JTextField txtCuit) {
        this.txtCuit = txtCuit;
    }

    public JTextField getTxtDir() {
        return txtDir;
    }

    public void setTxtDir(JTextField txtDir) {
        this.txtDir = txtDir;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JTextField getTxtMail() {
        return txtMail;
    }

    public void setTxtMail(JTextField txtMail) {
        this.txtMail = txtMail;
    }

    public JTextField getTxtRazonSocial() {
        return txtRazonSocial;
    }

    public void setTxtRazonSocial(JTextField txtRazonSocial) {
        this.txtRazonSocial = txtRazonSocial;
    }

    public JTextField getTxtTel() {
        return txtTel;
    }

    public void setTxtTel(JTextField txtTel) {
        this.txtTel = txtTel;
    }

    public JTextField getTxtTel2() {
        return txtTel2;
    }

    public void setTxtTel2(JTextField txtTel2) {
        this.txtTel2 = txtTel2;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fraBusqueda = new javax.swing.JPanel();
        txtClienteBusq = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtRazonSocial = new javax.swing.JTextField();
        lblRazonSocial = new javax.swing.JLabel();
        txtCuit = new javax.swing.JTextField();
        txtDir = new javax.swing.JTextField();
        lblDir = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        lblTel2 = new javax.swing.JLabel();
        txtTel2 = new javax.swing.JTextField();
        lblMail = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        lblProvincia = new javax.swing.JLabel();
        lblLocalidad = new javax.swing.JLabel();
        cboProvincia = new javax.swing.JComboBox();
        cboLocalidad = new javax.swing.JComboBox();
        lblId = new javax.swing.JLabel();
        lblCuit = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setName("ABMCLI"); // NOI18N

        fraBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        fraBusqueda.setName("fraBusqueda"); // NOI18N

        txtClienteBusq.setName("txtCliente"); // NOI18N
        txtClienteBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteBusqActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente:");

        javax.swing.GroupLayout fraBusquedaLayout = new javax.swing.GroupLayout(fraBusqueda);
        fraBusqueda.setLayout(fraBusquedaLayout);
        fraBusquedaLayout.setHorizontalGroup(
            fraBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fraBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(txtClienteBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        fraBusquedaLayout.setVerticalGroup(
            fraBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fraBusquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fraBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteBusq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtRazonSocial.setName("txtRazonSocial"); // NOI18N

        lblRazonSocial.setText("Razón Social:");

        txtCuit.setName("txtRazonSocial"); // NOI18N

        txtDir.setName("txtRazonSocial"); // NOI18N

        lblDir.setText("Dirección:");

        lblTel.setText("Teléfono:");

        txtTel.setName("txtRazonSocial"); // NOI18N

        lblTel2.setText("Tel. Alternativo:");

        txtTel2.setName("txtRazonSocial"); // NOI18N

        lblMail.setText("Email:");

        txtMail.setName("txtRazonSocial"); // NOI18N
        txtMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMailActionPerformed(evt);
            }
        });

        lblProvincia.setText("Provincia:");

        lblLocalidad.setText("Localidad:");

        cboProvincia.setSelectedItem("Seleccione la Provincia...");
        cboProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProvinciaItemStateChanged(evt);
            }
        });
        cboProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboProvinciaActionPerformed(evt);
            }
        });

        cboLocalidad.setSelectedItem("Seleccione la Localidad...");

        lblId.setText("ID Cliente:");

        lblCuit.setText("CUIT:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMail)
                    .addComponent(lblLocalidad)
                    .addComponent(lblTel)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRazonSocial)
                            .addComponent(lblProvincia)
                            .addComponent(lblDir)
                            .addComponent(lblCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblId))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblTel2))
                                        .addComponent(cboLocalidad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cboProvincia, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtTel2)))
                            .addComponent(txtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazonSocial)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDir))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProvincia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocalidad)
                    .addComponent(cboLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTel)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMail))
                .addGap(29, 29, 29))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.setName("btn"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.setName("btn"); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(fraBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(94, 94, 94)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(fraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnGuardar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClienteBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteBusqActionPerformed
           presenter.getClienteHandler().stateChanged(new ChangeEvent(this));
    }
    
        // TODO add your handling code here:         presenter.getClienteHandler().stateChanged(new ChangeEvent(this));     }//GEN-LAST:event_txtClienteBusqActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }
    
        // TODO add your handling code here:         System.exit(0);     }//GEN-LAST:event_btnSalirActionPerformed

        private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
            Icon Icon = null;
            boolean continuar = true;

            if (modo == 1){
                if(this.getTxtCuit().getText().trim().length()==0){
                    JOptionPane.showMessageDialog(this, "Debe ingresar el CUIT", "Alta Cliente", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getTxtCuit().requestFocus();
                }
                if(this.getTxtRazonSocial().getText().trim().length()==0 && continuar){
                    JOptionPane.showMessageDialog(this, "Debe informar la Razon Social", "Alta Cliente", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getTxtRazonSocial().requestFocus();
                }
                if(this.getTxtDir().getText().trim().length()==0 && continuar){
                    JOptionPane.showMessageDialog(this, "Debe ingresar la dirección", "Alta Cliente", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getTxtDir().requestFocus();
                }
                if(this.getCboLocalidad().getSelectedIndex() ==-1 && continuar){
                    JOptionPane.showMessageDialog(this, "Debe ingresar la localidad", "Alta Cliente", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getCboLocalidad().requestFocus();
                }                  
            }else if(modo == 2){
                if(this.getTxtCuit().getText().trim().length()==0){
                    JOptionPane.showMessageDialog(this, "Debe ingresar el CUIT", "Modificar Cliente", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getTxtCuit().requestFocus();
                }
                if(this.getTxtRazonSocial().getText().trim().length()==0 && continuar){
                    JOptionPane.showMessageDialog(this, "Debe informar la Razon Social", "Modificar Cliente", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getTxtRazonSocial().requestFocus();
                }
                if(this.getTxtDir().getText().trim().length()==0 && continuar){
                    JOptionPane.showMessageDialog(this, "Debe ingresar la dirección", "Modificar Cliente", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getTxtDir().requestFocus();
                }
                if(this.getCboLocalidad().getSelectedIndex() ==-1 && continuar){
                    JOptionPane.showMessageDialog(this, "Debe ingresar la localidad", "Modificar Cliente", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getCboLocalidad().requestFocus();
                }  
            }else{
                if(this.getTxtCuit().getText().trim().length()==0){
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente", "Borrar Cliente", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getTxtCuit().requestFocus();
                }
            }
            if(continuar){
                presenter.getPres().stateChanged(new ChangeEvent(this));
            }
        }
        
        // TODO add your handling code here:         presenter.getPres().stateChanged(new ChangeEvent(this));     }//GEN-LAST:event_btnGuardarActionPerformed

        // TODO add your handling code here:         presenter.getClienteHandler().stateChanged(new ChangeEvent(this));     }                                              

    private void cboProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboProvinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboProvinciaActionPerformed

        // TODO add your handling code here:         presenter.getClienteHandler().stateChanged(new ChangeEvent(this));     }                                              

    private void cboProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProvinciaItemStateChanged
        presenter.getLocalidadHandler().stateChanged(new ChangeEvent(this));
    
}//GEN-LAST:event_cboProvinciaItemStateChanged

        // TODO add your handling code here:         presenter.getPres().stateChanged(new ChangeEvent(this));     }                                          

private void txtMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMailActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtMailActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cboLocalidad;
    private javax.swing.JComboBox cboProvincia;
    private javax.swing.JPanel fraBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCuit;
    private javax.swing.JLabel lblDir;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLocalidad;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTel2;
    private javax.swing.JTextField txtClienteBusq;
    private javax.swing.JTextField txtCuit;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTel2;
    // End of variables declaration//GEN-END:variables

    void notificar(boolean resultado) {
       
      Icon Icon = null;
      if(resultado){
        JOptionPane.showMessageDialog(this, "Operación realizada con exito", "Cliente", JOptionPane.INFORMATION_MESSAGE,   Icon);  
      }
    }

    void notificarMensaje(String mensaje, int tipoMensaje) {
        Icon Icon = null;
        JOptionPane.showMessageDialog(this,mensaje, "Envios", tipoMensaje,   Icon);  
        
    }
}
