/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sge.vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author Marcos
 */
public class JABMTransporteViewer extends javax.swing.JInternalFrame {

    /**
     * Creates new form JABMTransporteViewer
     */        
        
    private JABMTransportePresenter presenter;
    private Integer modo; 
    
    public JABMTransporteViewer(int modo) {
        this.modo = modo;
        initComponents();
        if (modo == 1) {
            this.setTitle("Alta Transportista");
            btnGuardar.setText("Guardar");
            fraBusqueda.setVisible(false);
            txtId.setVisible(false);
            lblId.setVisible(false);
        }else if (modo == 2) {    
            this.setTitle("Modificar Transportista");
            btnGuardar.setText("Modificar");   
            txtId.setEnabled(false);
        }else if (modo == 3) {
            this.setTitle("Baja Transportista");
            btnGuardar.setText("Borrar");
            txtId.setEnabled(false);
            txtDir.setEditable(false);
            txtCuit.setEditable(false);
            txtRazonSocial.setEditable(false);
            cboTipo.setEnabled(false);
            txtTel.setEditable(false); 
        }
                //Redimensiona la ventana
        pack();
        
        
        presenter = new JABMTransportePresenter(this);  
   
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();  
        //obtenemos el tamaño de la ventana  
        Dimension ventana = this.getSize();  
        //para cntrar la ventana lo hacemos con el siguiente calculo  
        this.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 2);  
    }

    public JComboBox getCboTipo() {
        return cboTipo;
    }

    public void setCboTipo(JComboBox cboTipo) {
        this.cboTipo = cboTipo;
    }

    public JTextField getTxtCuit() {
        return txtCuit;
    }

    public void setTxtCuit(JTextField txtCuit) {
        this.txtCuit = txtCuit;
    }

    public JTextField getTxtDir() {
        return txtDir;
    }

    public void setTxtDir(JTextField txtDir) {
        this.txtDir = txtDir;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }

    public JTextField getTxtRazonSocial() {
        return txtRazonSocial;
    }

    public void setTxtRazonSocial(JTextField txtRazonSocial) {
        this.txtRazonSocial = txtRazonSocial;
    }

    public JTextField getTxtTel() {
        return txtTel;
    }

    public void setTxtTel(JTextField txtTel) {
        this.txtTel = txtTel;
    }

    public JTextField getTxtTransporteBusq() {
        return txtTransporteBusq;
    }

    public void setTxtTransporteBusq(JTextField txtTransporteBusq) {
        this.txtTransporteBusq = txtTransporteBusq;
    }

    public Integer getModo() {
        return modo;
    }

    public void setModo(Integer modo) {
        this.modo = modo;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        fraBusqueda = new javax.swing.JPanel();
        txtTransporteBusq = new javax.swing.JTextField();
        lblTransporte = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtRazonSocial = new javax.swing.JTextField();
        lblRazonSocial = new javax.swing.JLabel();
        lblCuit = new javax.swing.JLabel();
        txtCuit = new javax.swing.JTextField();
        txtDir = new javax.swing.JTextField();
        lblDir = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setIconifiable(true);
        setName("ABMTRA"); // NOI18N

        btnSalir.setText("Salir");
        btnSalir.setName("btn"); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setName("btn"); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        fraBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        fraBusqueda.setName("fraBusqueda"); // NOI18N

        txtTransporteBusq.setName("txtCliente"); // NOI18N
        txtTransporteBusq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransporteBusqActionPerformed(evt);
            }
        });

        lblTransporte.setText("Transporte:");

        javax.swing.GroupLayout fraBusquedaLayout = new javax.swing.GroupLayout(fraBusqueda);
        fraBusqueda.setLayout(fraBusquedaLayout);
        fraBusquedaLayout.setHorizontalGroup(
            fraBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fraBusquedaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTransporte)
                .addGap(43, 43, 43)
                .addComponent(txtTransporteBusq, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        fraBusquedaLayout.setVerticalGroup(
            fraBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fraBusquedaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fraBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTransporteBusq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTransporte))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtRazonSocial.setName("txtRazonSocial"); // NOI18N

        lblRazonSocial.setText("Razón Social:");

        lblCuit.setText("CUIT:");

        txtCuit.setName("txtRazonSocial"); // NOI18N

        txtDir.setName("txtRazonSocial"); // NOI18N

        lblDir.setText("Dirección:");

        lblTel.setText("Teléfono:");

        txtTel.setName("txtRazonSocial"); // NOI18N

        lblId.setText("Id Transporte:");
        lblId.setName("lblId"); // NOI18N

        cboTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Transportista", "Comisionista" }));

        jLabel1.setText("Tipo Transporte:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCuit)
                    .addComponent(jLabel1)
                    .addComponent(lblRazonSocial)
                    .addComponent(lblDir)
                    .addComponent(lblTel)
                    .addComponent(lblId))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCuit)
                        .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCuit)
                    .addComponent(txtCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRazonSocial)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTel)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fraBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
}//GEN-LAST:event_btnSalirActionPerformed

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
            Icon Icon = null;
            boolean continuar = true;

            if (modo == 1){
                if(this.getTxtCuit().getText().trim().length()==0){
                    JOptionPane.showMessageDialog(this, "Debe ingresar el CUIT", "Alta Transporte", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getTxtCuit().requestFocus();
                }
                if(this.getTxtRazonSocial().getText().trim().length()==0 && continuar){
                    JOptionPane.showMessageDialog(this, "Debe informar la Razon Social", "Alta Transporte", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getTxtRazonSocial().requestFocus();
                }
                if(this.getTxtDir().getText().trim().length()==0 && continuar){
                    JOptionPane.showMessageDialog(this, "Debe ingresar la dirección", "Alta Transporte", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getTxtDir().requestFocus();
                }
                if(this.getCboTipo().getSelectedIndex() ==-1 && continuar){
                    JOptionPane.showMessageDialog(this, "Debe ingresar el tipo de transporte", "Alta Transporte", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getCboTipo().requestFocus();
                }                  
            }else if(modo == 2){
                if(this.getTxtCuit().getText().trim().length()==0){
                    JOptionPane.showMessageDialog(this, "Debe ingresar el CUIT", "Modificar Transporte", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getTxtCuit().requestFocus();
                }
                if(this.getTxtRazonSocial().getText().trim().length()==0 && continuar){
                    JOptionPane.showMessageDialog(this, "Debe informar la Razon Social", "Modificar Transporte", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getTxtRazonSocial().requestFocus();
                }
                if(this.getTxtDir().getText().trim().length()==0 && continuar){
                    JOptionPane.showMessageDialog(this, "Debe ingresar la dirección", "Modificar Transporte", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getTxtDir().requestFocus();
                }
                if(this.getCboTipo().getSelectedIndex() ==-1 && continuar){
                    JOptionPane.showMessageDialog(this, "Debe ingresar el tipo de transporte", "Modificar Transporte", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getCboTipo().requestFocus();
                }      
            }else{
                if(this.getTxtCuit().getText().trim().length()==0){
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un Transporte", "Borrar Transporte", JOptionPane.ERROR_MESSAGE,   Icon);
                    continuar=false;
                    this.getTxtCuit().requestFocus();
                }
            }
            if(continuar){
                presenter.getGuardarMedioEnvio().stateChanged(new ChangeEvent(this));
            }
        
        
}//GEN-LAST:event_btnGuardarActionPerformed

private void txtTransporteBusqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransporteBusqActionPerformed
            if(this.txtTransporteBusq.getText().trim().length()>0){
                this.getTxtRazonSocial().setText("");
                presenter.getBuscarMedioEnvioHandler().stateChanged(new ChangeEvent(this));
            }
    
    
}//GEN-LAST:event_txtTransporteBusqActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cboTipo;
    private javax.swing.JPanel fraBusqueda;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCuit;
    private javax.swing.JLabel lblDir;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JLabel lblTel;
    private javax.swing.JLabel lblTransporte;
    private javax.swing.JTextField txtCuit;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtRazonSocial;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtTransporteBusq;
    // End of variables declaration//GEN-END:variables
    void notificar(boolean resultado) {
       
        Icon Icon = null;
        if(resultado){
            JOptionPane.showMessageDialog(this, "Operación realizada con exito", "Transporte", JOptionPane.INFORMATION_MESSAGE,   Icon);  
        }
    }
    
    void notificarException(Exception ex) {
      Icon Icon = null;
      JOptionPane.showMessageDialog(this, ex.toString(), "Transporte", JOptionPane.ERROR_MESSAGE,   Icon);  
    }
    void notificarMensaje(String mensaje, int tipoMensaje) {
        Icon Icon = null;
        JOptionPane.showMessageDialog(this,mensaje, "Envios", tipoMensaje,   Icon);  
        
    }
}