/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JRegistroSalidaViewer.java
 *
 * Created on 30/05/2012, 21:30:03
 */
package sge.vista;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.GregorianCalendar;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import sge.exception.ConectividadException;

/**
 *
 * @author Propietario
 */
public class JRegistroSalidaViewer extends javax.swing.JInternalFrame {
    private JRegistroSalidaPresenter presenter;
    /** Creates new form JRegistroSalidaViewer */
    public JRegistroSalidaViewer() {
        String[] cabeceras ={"id", "nrolinea","Cliente","Dirección","Nro. factura","Cant. bultos"};
        boolean[] editables={false,false,false,false,false,false};
        
        initComponents();
        SimpleDateFormat formatea = new SimpleDateFormat("dd/MM/yyyy");
        this.txtFecha.setText(formatea.format(GregorianCalendar.getInstance().getTime()));
        
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();  
        //obtenemos el tamaño de la ventana  
        Dimension ventana = this.getSize();  
        //para cntrar la ventana lo hacemos con el siguiente calculo  
        this.setLocation((pantalla.width - ventana.width) / 2, (pantalla.height - ventana.height) / 2);  
        
        presenter= new JRegistroSalidaPresenter(this);
        
        
        GenericoTableModel aTableModel = new GenericoTableModel();
        aTableModel.setCabeceras(cabeceras);
        aTableModel.setEditables(editables);
        this.tblEnvio.setModel(aTableModel);  
        this.tblEnvio.getColumnModel().getColumn(0).setMaxWidth(0);
        this.tblEnvio.getColumnModel().getColumn(0).setMinWidth(0);
        this.tblEnvio.getColumnModel().getColumn(0).setPreferredWidth(0);        
        this.tblEnvio.getColumnModel().getColumn(1).setMaxWidth(0);
        this.tblEnvio.getColumnModel().getColumn(1).setMinWidth(0);
        this.tblEnvio.getColumnModel().getColumn(1).setPreferredWidth(0);
        
        this.txtNumeroEnvio.requestFocus();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumeroEnvio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnvio = new javax.swing.JTable();
        lblFecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        txtFechaViaje = new javax.swing.JTextField();
        cmdCancelar = new javax.swing.JButton();
        cmdEnviar = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setName("REGDES"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda de envío"));

        jLabel1.setText("Envio:");

        txtNumeroEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroEnvioActionPerformed(evt);
            }
        });
        txtNumeroEnvio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroEnvioKeyTyped(evt);
            }
        });

        jLabel2.setText("Fecha:");

        txtFecha.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtNumeroEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Envío"));

        tblEnvio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEnvio.setRowHeight(20);
        jScrollPane1.setViewportView(tblEnvio);

        lblFecha.setText("Fecha:");

        jLabel3.setText("Transporte:");

        txtRazonSocial.setEditable(false);

        txtFechaViaje.setEditable(false);
        txtFechaViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaViajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblFecha))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addComponent(txtFechaViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmdCancelar.setText("Cancelar");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });

        cmdEnviar.setText("Enviar");
        cmdEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEnviarActionPerformed(evt);
            }
        });
        cmdEnviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmdEnviarKeyTyped(evt);
            }
        });

        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(cmdEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(cmdSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSalir)
                    .addComponent(cmdEnviar)
                    .addComponent(cmdCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getTxtFechaViaje() {
        return txtFechaViaje;
    }

    public JTextField getTxtRazonSocial() {
        return txtRazonSocial;
    }

    
    
        private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
            this.txtNumeroEnvio.setText("");
            this.txtFechaViaje.setText("");
            this.txtRazonSocial.setText("");
            GenericoTableModel aModel= (GenericoTableModel) this.tblEnvio.getModel();
            aModel.limpiar();  
            this.tblEnvio.addNotify();        
            this.txtNumeroEnvio.requestFocus();
            presenter.getCancelarEnvioHandler().stateChanged(new ChangeEvent(this));
            
        }
        // TODO add your handling code here:}//GEN-LAST:event_cmdCancelarActionPerformed

        private void cmdEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEnviarActionPerformed
            
            if(this.tblEnvio.getRowCount()> 0){
                presenter.getRegistrarDespachoHandler().stateChanged(new ChangeEvent(this));
                this.txtNumeroEnvio.setText("");
                this.txtFechaViaje.setText("");
                this.txtRazonSocial.setText("");
                GenericoTableModel aModel= (GenericoTableModel) this.tblEnvio.getModel();
                aModel.limpiar();  
                this.tblEnvio.addNotify();        
                this.txtNumeroEnvio.requestFocus();
                
            }else{
                
                notificarMensaje("No ha buscado el envio a despachar", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }    
        // TODO add your handling code here:     }//GEN-LAST:event_cmdEnviarActionPerformed

        private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
            this.dispose();
        }    
        // TODO add your handling code here:         this.dispose();     }//GEN-LAST:event_cmdSalirActionPerformed

    private void txtNumeroEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroEnvioActionPerformed
        // TODO add your handling code here:
        if(this.txtNumeroEnvio.getText().trim().length()>= 0){            
            GenericoTableModel aModel= (GenericoTableModel) this.tblEnvio.getModel();
            aModel.limpiar();  
            
            this.tblEnvio.addNotify();
            presenter.getBuscarEnvioHandler().stateChanged(new ChangeEvent(this));
            tblEnvio.changeSelection(0, 1, false, false);
            this.cmdEnviar.requestFocus();
        }else{
            this.txtNumeroEnvio.requestFocus();
        }
            
    }//GEN-LAST:event_txtNumeroEnvioActionPerformed

    private void txtNumeroEnvioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroEnvioKeyTyped
        // TODO add your handling code here:
      char caracter = evt.getKeyChar();
      // Verificar si la tecla pulsada no es un digito
      if( !Character.isDigit(caracter)){      
         evt.consume();  // ignorar el evento de teclado
      }
    }

    public JTable getTblEnvio() {
        return tblEnvio;
    }

    public JTextField getTxtNumeroEnvio() {
        return txtNumeroEnvio;
    }//GEN-LAST:event_txtNumeroEnvioKeyTyped

    private void txtFechaViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaViajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaViajeActionPerformed

    private void cmdEnviarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmdEnviarKeyTyped
        // TODO add your handling code here:
        java.awt.event.ActionEvent evt2 = null;
        this.cmdEnviarActionPerformed(evt2);
    }//GEN-LAST:event_cmdEnviarKeyTyped

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdEnviar;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JTable tblEnvio;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFechaViaje;
    private javax.swing.JTextField txtNumeroEnvio;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables

    void notificarException(ConectividadException ex) {
        Icon Icon = null;
        JOptionPane.showMessageDialog(this,ex.toString(), "Envios", JOptionPane.ERROR_MESSAGE,   Icon);  
    }

    void notificarMensaje(String mensaje, int tipoMensaje ) {
        
        Icon Icon = null;
        JOptionPane.showMessageDialog(this,mensaje, "Envios", tipoMensaje,   Icon);  
        
    }
}
